---
driver:
  name: docker
  use_sudo: false
  privileged: true

verifier:
  name: inspec
  format: doc

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: jenkins

platforms:
#  - name: ubuntu-16.04
#    driver_config:
#      provision_command:
#        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
#      run_command: /sbin/init
#      privileged: true
#      pid_one_command: /usr/lib/systemd/systemd
  - name: centos-7
    driver_config:
      image: centos:7
      provision_command:
        - yum -y install initscripts
      platform: rhel
      run_command: /sbin/init
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    provisioner:
      vendor_path: vendor
      state_top:
        base:
          '*':
            - sun-java
            - sun-java.env
            - jenkins.plugins
            - jenkins.setup
            - jenkins.jobs
            - nginx
            - nginx.ng
            - nginx.ng.config
            - nginx.ng.service
            - jenkins.nginx
      pillars:
        top.sls:
          base:
            '*':
              - jenkins
              - nginx
              - sun-java
        sun-java.sls:
          java:
            version_name: jdk1.8.0_131
            source_url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
            source_hash: 62b215bdfb48bace523723cdbb2157c665e6a25429c73828a32f00e587301236
        jenkins.sls:
          jenkins:
            lookup:
              java_executable: /usr/lib/java/bin/java
              jenkins_port: 8080
              port: 80
              home: /var/lib/jenkins
              user: jenkins
              group: www-data
              nginx_user: jenkins
              server_name: localhost
              master_url: http://localhost:8080
              use_upstart: False
              allow_wizard: False
              admin_username: admin
              admin_password: admin123
              plugins:
                timeout: 90
                installed:
                  - greenballs
                  - matrix-auth
              pkgs:
                - jenkins
        nginx.sls:
          nginx:
            user_auth_enabled: False
            default_user: jenkins
            webuser: jenkins
            use_upstart: False
            use_sysvinit: False
            ng:
              pid_file: /var/run/nginx.pid
